version: '3.8'

services:
  backend:
    build: 
      context: ./chat-room-backend
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/chat-room?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - JWT_SECRET=votreclésecrete123456789
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - chat-network
    volumes:
      - backend-uploads:/app/uploads
    restart: always

  frontend:
    build:
      context: ./chat-room-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - chat-network
    restart: always

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=chat-room
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - chat-network
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_password"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  chat-network:
    driver: bridge

volumes:
  mysql-data:
  backend-uploads:
